MySQL:
  url: ''
  username: ''
  passwords: ''
ActionBar:
  format: '&f&lNext: {cooldown} &e{time}s'
  cooldown: '⬤'
  phase: 10
  player:
    ht: '#2205FF'
    dt: '#FF0505'
AFKRegion:
AFKReward:
  VIP:
    permission: 'afk.vip'
    reward: '3-5'
  MVP:
    permission: 'afk.mvp'
    reward: '6-9'
  MEMBER:
    permission: 'afk.member'
    reward: '1-3'
AFKReward_Default: MEMBER
AFKReward_Phase: '1000' # cứ mỗi 1s thì sẽ chạy reward 1 lần
IAS: '10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34,37,38,39,40,41,42,43'
Message:
  PermissionError: '&c Bạn Ko có quyền để chạy lệnh!'
  BuySuccess:
    - '&d&m-------------------'
    - '&a Mua Thành Công {item}'
    - '&d&m-------------------'
  FullInventory: '&c Túi Đồ Đã Đầy!'
ShopItemLore: # lore đc thêm vào item trong shop
  - ''
  - '&bPrice: &6{price}'
  - ''
  - '&eClick Để Mua!'
ShopItemLoading:
  material: PLAYER_HEAD
  display: '&cLoading...'
  lore: []
  value: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmFkYzA0OGE3Y2U3OGY3ZGFkNzJhMDdkYTI3ZDg1YzA5MTY4ODFlNTUyMmVlZWQxZTNkYWYyMTdhMzhjMWEifX19'
